version: 2.1
jobs:
  ami-job1: 
    docker:
      - image: circleci/node:11.10.1-browsers 
    steps:
      - checkout
      - run: |
           sleep 10 &
           echo "This is command 2" &
           echo "This is command 3"
  ami-job2:
    docker:
      - image: circleci/node:11.10.1-browsers
    steps:
      - checkout
      - run: echo "This is ami-job2"
  main-job1:
    docker:
      - image: circleci/node:11.10.1-browsers
    steps:
      - checkout
      - run: echo "This is main-job1"   
      
workflows:
  version: 2
  ami:
    jobs:
      - ami-job1

      
