version: 2.1
orbs:
  howdy: circleci/hello-build@0.0.9 # uses the circleci/buildpack-deps Docker image
workflows:
    build-test-deploy:
      jobs:
        - howdy/hello-build:    
            to: Viji
