version: 2.1
orbs:
  howdy: circleci/hello-build@0.0.10
jobs:
  build: 
    docker:
      - image: circleci/node:11.10.1-browsers 
    steps:
      - setup_remote_docker
      - checkout
      - run: echo "This is where we build..."
  test:
    machine: true
    steps:
      - checkout
      - run: echo "This is where we test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - howdy/hello-build:
          to: aaron
      - test
      
