version: 2.1
jobs:
  ami-job1: 
    docker:
      - image: circleci/node:11.10.1-browsers 
    steps:
      - checkout
      - run: echo "This is ami-job1"
  ami-job2:
    docker:
      - image: circleci/node:11.10.1-browsers
    steps:
      - checkout
      - run: echo "This is ami-job2"
  main-job1:
    docker:
      - image: circleci/node:11.10.1-browsers
    steps:
      - checkout
      - run: echo "This is main-job1"   
      
workflows:
  version: 2
  ami:
    jobs:
      - ami-job1:
          filters:
            tags:
              only: /^AMI.*/
      - ami-job2:
          filters:
            tags:
              only: /^AMI.*/
          requires:
            - ami-job1
  main:
    jobs:
      - main-job1
      
