jobs:
  build:
    docker:
      - image: quay.io/pantheon-public/build-tools-ci:latest
    working_directory: ~/sitedir
    environment:
      TZ: /usr/share/zoneinfo/America/Los_Angeles
      BUILD_TOOLS_VERSION: dev-option-for-no-force
      TERM: dumb
      PANTHEON_REPO_DIR: /tmp/pantheon_repo
    steps:
      - run: echo "hello"
orbs:
  jira: circleci/jira@1.0.6
  jq: circleci/jq@1.9.0
version: 2.1
workflows:
  build:
    jobs:
      - build:
          pre-steps:
            - run:
                command: echo "sudo rm -f $(command -v jq)"
          post-steps:
            - jira/notify
