version: 2
jobs:
  delivery:
    machine: true 
    steps:
    - checkoutt
    - run:
        command: chef gem install dnsimple
    - run:
        command: delivery local all

workflows:
  version: 2
  build_and_test:
    jobs:
      - delivery
