jobs:
  build:
    docker:
      - image: quay.io/pantheon-public/build-tools-ci:5.x
      working_directory: ~/sitedir
    environment:
      TZ: /usr/share/zoneinfo/America/Los_Angeles
      BUILD_TOOLS_VERSION: dev-option-for-no-force
      TERM: dumb
      PANTHEON_REPO_DIR: /tmp/pantheon_repo
    steps:
      - run: echo "hello"
orbs:
  jira: circleci/jira@1.0.5
version: 2.1
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify
