version: 2
jobs:
  build:
    docker:
      - image: docker.fwsas.com/build-base-image/c-build:1.0
        auth:
          username: ${USERNAME}
          password: ${PASSWORD}
    steps:
      - checkout
  run-make:
    docker:
      - image: docker.fwsas.com/build-base-image/c-build:1.0
    steps:
      - run: null
        name: Creating Build Files & Binary Files
        command: |
          make clean
          make
  Testing:
    docker:
      - image: docker.fwsas.com/build-base-image/c-build:1.0
    steps:
      - run:
          name: Run App
          command: ./bin/mainapp

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: security-group
      - run-make
      - Testing

