version: 2.1
orbs:
  hello-build: circleci/hello-build@0.0.14
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
    - checkout
    - hello-build/hello-triggerer:
        to: $CIRCLE_BRANCH
workflows:
  sample-workflow:
    jobs:
      - build
