version: 2.1
orbs:
  howdy: circleci/hello-build@0.0.9 # uses the circleci/buildpack-deps Docker image
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - howdy/hello-build:    

          
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - howdy/hello-build:
#           to: aaron
