version: 2
jobs:
  delivery:
    docker:
    - image: chef/chefdk:3
    steps:
    - checkout
    - run:
        command: chef gem install dnsimple
    - run:
        command: delivery local all

workflows:
  version: 2
  build_and_test:
    jobs:
      - delivery
